let scribbling = false;
let lastElementID = 0;
/* Palette generated by Material Palette _ materialpalette.com/blue_grey/teal */

const dark_primary_color    = '#00363a';
const default_primary_color = '#006064';
const light_primary_color   = '#428e92';

const dark_secondary_color    = '#002f6c';
const default_secondary_color = '#01579b';
const light_secondary_color   = '#4f83cc';

const accent_color          = '#0000ff';
const accent_secondary_color ='#0000ff';
const light_primary_text_color    ='#FFFFFF';
const dark_primary_text_color ='#212121'; 
const accent_text_color       ='#009688'; 
const secondary_text_color  ='#757575';
const divider_color         ='#BDBDBD';

const md500_red='#d50000b0';
const md500_green='#00c853b0';
const md500_amber='#ffab00b0';

